### ISSUE TITLE
路过..关于Aws lightsail有点问题..

### ISSUE THREAD

**Issue by Tarhyru** [OysterQAQ/Pixiv-Illustration-Collection#1]
Aws lightsail 这个反向代理绕过盗链具体是怎么一个操作能详细讲讲么..不是很懂JAVA...
讲个大概思路就行了...
我自己实现过在一个GET接口将URL转成16进制作为参数传进去，然后附带referer请求到图片返回给前台得方式...
实际上，前端可以直接设置强制不添加referer....
浏览器默认就会把referer指向图片地址本身...就不会触发基于referer的防盗链机制了..
meta里指定就行..
我个人喜欢在img里添加referrefpolicy="no-referrer"...
除了IE其它浏览器都认这种方式...IE得话认在meta里指定....
另外爬取三天前是什么考量...
P站日榜，周榜，等每天上午11点左右更新...一般每天爬取设置成11点半就可以爬取到昨日的榜单呀？

**Comment by OysterQAQ** [comment]
Referer请求头是在后端进行验证的，和java关系不大，具体查询nginX防盗链处理，可以指定referer头，验证不通过返回403，只与高级会员_(:з」∠)_项目里有直接用高级会员token与手动排序两个方案，详见源码

**Comment by OysterQAQ** [comment]
排行榜日期的问题，你可以去看一下p站最近一天的稳定排行，是在哪一天

**Comment by Tarhyru** [comment]
@OysterQAQ 
所以其实我想问的是你是通过什么方式来绕过P站的referer认证的....
我看到代码里搜索调用的接口了..直接用会提示没有token..你是把自己账号的token写进去了么..
日期的话...我稳定爬了一个月的P站日榜,周榜,新人榜和男性榜单以及R18日榜，周榜，男性榜...
都是每天上午十一点半爬取...虽然部分内容会有重复但每天内容顺序都是有区别的...
比如现在..北京时间，10月7号凌晨2点，现在去看榜单日期的话是10月5号..好似三天前..
但是，当北京时间10月7号，早上11点左右的时候，榜单日期会更新成10月6号的...
部分图片可能会重复但是十一点后的顺序肯定和现在是不一样的...
也就是说每天11点后爬取的话，应该是取昨天的..不过你要是凌晨5点取得话的确是三天前...

**Comment by Tarhyru** [comment]
@OysterQAQ 
这块还真是知识盲区....我只用过基于SSH的反向代理....
我理解的反向代理是在本地把端口代理给远端...
比如，把服务端的端口代理给堡垒机..然后堡垒机像外界提供服务..
Nginx的反向代理...在这个过程中怎么添加请求头呢....
把自己代理到p站上去....?好像不太对....解析所有指向p站的url再添加？
但是图片url直接是指向p站的..按理说应该不会通过自己架的Ngix呀？...这个要怎么拦截呢....
