### ISSUE TITLE
随机图片api

### ISSUE THREAD

**Issue by AccMoment** [OysterQAQ/Pixiv-Illustration-Collection#17]
此api无法使用，是否可以修复？

**Comment by OysterQAQ** [comment]
会的 十一月新版上线会发布新的api文档

**Comment by OysterQAQ** [comment]
已经上线，地址https://api.pixivic.com/illusts/random?detail=true&range=0.01&urlType=original&illustType=illust&ratio=1:1&maxSanityLevel=2

**Comment by AccMoment** [comment]
有没有新的api文档。。

**Comment by AccMoment** [comment]
还有这个链接跳转之后会出现无法访问

**Comment by OysterQAQ** [comment]
十一月3.0上线后统一整理发布

**Comment by OysterQAQ** [comment]
确实，毕竟用的是别人的反向代理

**Comment by AccMoment** [comment]
好的，谢谢
