### ISSUE TITLE
关于伪造请求头更好的解决办法

### ISSUE THREAD

**Issue by WangWenBin2017** [OysterQAQ/Pixiv-Illustration-Collection#9]
楼主在吗，图床可以使用pixiv.cat的免费公共反向代理，无需伪造请求头，可直接用，只是把域名pximg.net更换为https://i.pixiv.cat/ 即可。详细的使用方法:https://pixiv.cat/reverseproxy.html
哈哈，我就是吾爱破解给你帖子留言的那个，怕你看不见，又在gayhub上发一遍

**Comment by OysterQAQ** [comment]
伪造校验请求头和反向代理是两回事,我用的是pixiv app的api
